development:
  adapter: postgresql
  encoding: unicode
  database: database_name_development
  pool: 5
  host: localhost
  username: myapp
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: database_name_test
  pool: 5
  username: myapp
  password: password

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 